apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registrationentries.kubernetes.spire.summerwind.dev
spec:
  group: kubernetes.spire.summerwind.dev
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  names:
    kind: RegistrationEntry
    plural: registrationentries
    singular: registrationentry
  scope: Namespaced
